### ISSUE TITLE
Extending the `like` expansions?

### ISSUE THREAD

**Issue by yoavg** [allenai/pybart#16]
Consider this sentence, focusing on the word `including`:
```
PPV infection mainly causes reproductive clinical syndrome , including infertility , abortion , stillbirth , neonatal death , and reduced neonatal vitality
```

If it were `like`, we will be getting infertility, abortion, etc as `dobj` of `causes`, I think we should extend this behavior also to `including`, wdyt?

Another thing is that in the case of `like`, we get in addition to the `dobj` links, also `nsubj` links. Why do we get these?

**Comment by aryehgigi** [comment]
Sounds good to me.

re your question (why subject is added:)

consider just: "clinical syndrome". The amod relation causes a reversed nsubj relation.
now consider: "clinical syndrome, like infertility". Now that 'syndrome' has a new (nsubj) head, it will share it with 'infertility' because of the 'like' preposition.
I think it still makes sense, as if the adjective modifies each elaborated example. So it is like saying "what is clinical? the syndrom. but also the infertility, and the abortion, etc"

wdyt?

**Comment by yoavg** [comment]
hmm.. i am not sure i like this one, as i dont think it holds generally
(also, if you DO propagate nsubj, you have to propagate the amod relation
as well, which i dont think is happening now).

but in your example, i think that "infertility" is a "clinical syndrom" but
it is not necessarily "clinical", or rather "clinical infertility" might be
a very different class than "infertility".
