### ISSUE TITLE
Predicate Ellipsis issue

### ISSUE THREAD

**Issue by atmani-massinissa** [allenai/pybart#21]
Hello,

I found your paper very interesting and awesome, so thank you for this work.

I launched PyBART demo on the sentence : I like tea and you coffee.

But instead of adding a **nsubj** edge between _like_ and _you_, it added two **obj** edges between _you_ and _coffee_ to _like_
![ellipsis](https://user-images.githubusercontent.com/18259289/89179951-1525e280-d591-11ea-9457-6f308f7e8ad2.png)
I'm not sure, but you don't handle predicate ellipsis (missing copula or aux) in  Parallel structures, mentioned in the paper.
Or is it because the conjunction propagation rule is applied before the ellipsis rule.

Thanks

**Comment by aryehgigi** [comment]
Hi @atmani-massinissa 
Thank you so much for your feedback! 
Indeed we don't support elided predicates.

of course the propagation of objects in this case is wrong, but it occurs **due to the a parser mistake** (as you can see the UD tree itself is wrong, as it has the 'you' and 'coffee' connected to 'tea'. as if the sentence is saying: "I like tea and I like you and I like coffee", and in this (wrong) sence, the object propagation is correct).
compare CoreNLP:
![image](https://user-images.githubusercontent.com/5661975/89183478-f9760880-d59f-11ea-839d-0e4e78e2e981.png)

We are only as good as the parser we use.

Please let me know if you have any more questions.

**Comment by atmani-massinissa** [comment]
Thanks for your prompt reply.
