### ISSUE TITLE
not adding nsubj for acl?

### ISSUE THREAD

**Issue by yoavg** [allenai/pybart#59]
why no `nsubj` between `caused` and `sciatica`?

![image](https://user-images.githubusercontent.com/464308/234894578-ae30a7f6-a477-4162-a906-11960806ccf1.png)

**Comment by aryehgigi** [comment]
@yoavg do you remember what was the env+dataset and maybe the query? for reproducing..

**Comment by yoavg** [comment]
almost sure that pmcPubmed on spike staging.

**Comment by aryehgigi** [comment]
this is prevented because there is a restriction in the `acl` rule that says if head of the `acl` relation is a `subject` - we shouldnt proceed with this rule.
Unfortunately i don't exactly remember the incentive, but i imagine it was because former relations have made changes to around the `acl` relation such that performing the `acl` rule might be wrong, specifically if the head of the `acl` relation became a subject on its own we probably didn't want it to have its own subject or something of the sort.

now in the basic tree the head does not have an incoming `subject` relation, but there are two rules that happens before this one and causes the subject relation to form. the first is the `nmod:of` relation that induces a `compound` relation:
![image](https://user-images.githubusercontent.com/5661975/235599492-04ba0e17-89cb-4aba-860e-681261f5cc89.png)
-->
![image](https://user-images.githubusercontent.com/5661975/235600110-7c259a05-fbe6-48ca-8230-3b0e26d075d6.png)
the second is the `compound` causes the existing `subject` relation to be propagated to the `acl` head.
![Screenshot from 2023-05-02 09-59-33](https://user-images.githubusercontent.com/5661975/235605643-34189b52-1e46-4310-bc98-e8e7c7360b80.png)
-->
![Screenshot from 2023-05-02 09-59-25](https://user-images.githubusercontent.com/5661975/235605651-de21dff9-6225-4aa3-9021-708928ecb2cb.png)

what are our options:
1. accept this state: the disadvantage is that we wont always get the gain from this rule which means also inconsistency
2. remove the restriction from the `acl` rule (allow it to occur even if the head of the `acl` relation is a subject on its own): the disadvantage is that we would get the wrong changes that we are not sure what they where 
3. change the order of the rules (move the nmod+compound to later stage or the acl rule to earlier stage): the disadvantage is that we cant anticipate all the changes that would happen as all the rules interact in some way (im really against this one)
4. think of a way to add another restriction to the restriction: the disadvantages are that we wont be sure that we cover all cases and that we get to specific. also i dont have a concrete idea for how to do this.

@yoavg wdyt?

**Comment by yoavg** [comment]
a fifth approach is to distinguish between subject relations that appeared in the original graph, to ones that are a result of some rule.
